### ISSUE TITLE
Create project landing page

### ISSUE THREAD

**Issue by misslivirose** [misslivirose/Memory-Cache#4]
We want to set up a single landing page using GH pages to outline the project goals, areas of explorations, and links to helpful resources / ways for people to follow along with Memory Cache development

**Comment by katetaylormoz** [comment]
<img width="1886" alt="Screenshot 2023-11-24 at 1 46 07 PM" src="https://github.com/misslivirose/Memory-Cache/assets/100849201/9bf848e6-3348-4e6b-9551-7d25a4255a3c">

Mockup including landing page styling updates!

Changes:
- [ ] font to Work Sans
- [ ] new logo (SVG)
- [ ] banner image with overlay text
- [ ] change ‘Posts’ to ‘Updates’
- [ ] link color: #180AB8

**Comment by katetaylormoz** [comment]
![MemoryCache-Logo](https://github.com/misslivirose/Memory-Cache/assets/100849201/a0e27d3b-8dff-4188-abc5-4e612621b213)

**Comment by katetaylormoz** [comment]
![MemoryCache-BannerPrism](https://github.com/misslivirose/Memory-Cache/assets/100849201/a994f6e4-8f4f-49d9-8830-0119486a797e)

**Comment by misslivirose** [comment]
@katetaylormoz - do you have dimensions for the logo? Without specifying it seems a bit smaller in code than in the design.

**Comment by misslivirose** [comment]
🎉 Got the last styling issue in and John fixed the issue with the relative file path for the logo loading, so I'm going to resolve this and we can start making new issues as we make changes. Thank you for the amazing first pass on this page! We are live!
